export const routeObject = [
  { department: "Sub team", route: "/subheadsmin", team: "Ministry" },
  { department: "Leadership Effectiveness", route: "/leadeff", team: "Ministry" },
  { department: "Leadership Recruitment", route: "/lrecruit", team: "Ministry" },
  { department: "Leadership Training", route: "/leadtr", team: "Ministry" },
  { department: "Pastoral Care", route: "/pascares", team: "Ministry" },
  { department: "Discipleship, Bible Study and Prayer", route: "/dbsp", team: "Ministry" },
  { department: "Workforce Admin", route: "/wadata", team: "Ministry" },
  { department: "Call Centre", route: "/mincc", team: "Ministry" },
  { department: "Recruitment and Assimilation", route: "/rcam", team: "Ministry" },
  { department: "Career & Finance", route: "/crfn", team: "Ministry" },
  { department: "Medicals", route: "/mdmn", team: "Ministry" },
  { department: "Elders Care", route: "/edc", team: "Ministry" },
  { department: "Prison Ministry", route: "/prm", team: "Ministry" },
  { department: "Kids Support", route: "/kds", team: "Ministry" },
  { department: "House of Dorcas", route: "/hod", team: "Ministry" },
  { department: "Legal Aid", route: "/lea", team: "Ministry" },
  { route: "/benevolence", department: "Benevolence", team: "Membership" },
  { route: "/callcenter", department: "Call Center", team: "Membership" },
  { route: "/celebration", department: "Celebration", team: "Membership" },
  { route: "/ceremonies", department: "Ceremonies", team: "Membership" },
  { route: "/datamgt", department: "Data Management", team: "Membership" },
  { route: "/growthtrack", department: "Growth Track", team: "Membership" },
  { route: "/guestwelcome", department: "Guest Welcome", team: "Membership" },
  { route: "/infohub", department: "Info Hub", team: "Membership" },
  { route: "/interactor", department: "Interactors", team: "Membership" },
  { route: "/newconvert", department: "New Convert", team: "Membership" },
  { route: "/weddings", department: "Weddings", team: "Membership" },
  { route: "/kidszone", department: "Kids Zone", team: "Next Gen" },
  { route: "/stirhouse", department: "Stir House", team: "Next Gen" },
  {
    route: "/adminfacility",
    department: "Admin and Facility",
    team: "General Service",
  },
  {
    route: "/dmu",
    department: "Communications (DMU)",
    team: "General Service",
  },
  { route: "/finance", department: "Finance", team: "General Service" },
  {
    route: "/singles",
    department: "Singles Ministry",
    team: "Interactive Groups",
  },
  { route: "/wow", department: "Women of Wisdom", team: "Interactive Groups" },
  { route: "/moh", department: "Men of Harvest", team: "Interactive Groups" },
  {
    route: "/discipleevent",
    department: "Discipleship Event",
    team: "Maturity",
  },
  { route: "/grouppartner", department: "Group Partnership", team: "Maturity" },
  { route: "/testimony", department: "Testimony Capture", team: "Maturity" },
  { route: "/courses", department: "Courses HSDC", team: "Maturity" },
  {
    route: "/contentdev",
    department: "Content Development (Resources)",
    team: "Maturity",
  },
  {
    route: "/prayerbible",
    department: "Prayer and Bible Study",
    team: "Maturity",
  },
  { route: "/evangelism", department: "Evangelism", team: "Mission" },
  { route: "/godencounter", department: "God’s encounter", team: "Mission" },
  { route: "/hsap", department: "HSAP", team: "Mission" },
  { route: "/investinvite", department: "Invest and Invite", team: "Mission" },
  { route: "/nlp", department: "NLP", team: "Mission" },
  { route: "/publicity", department: "Publicity", team: "Mission" },
  {
    route: "/royalpriesthood",
    department: "Royal Priesthoods Community",
    team: "Districts",
  },
  {
    route: "/ogudualapere",
    department: "Ogudu/Alapere Community",
    team: "Districts",
  },
  { route: "/bethel", department: "Bethel Community", team: "Districts" },
  { route: "/harmony", department: "Harmony Community", team: "Districts" },
  {
    route: "/newgarage",
    department: "New Garage Community",
    team: "Districts",
  },
  { route: "/shomolu2", department: "Shomolu 2 Community", team: "Districts" },
  { route: "/oworo1", department: "Oworo 1 Community", team: "Districts" },
  { route: "/oworo2", department: "Oworo 2 Community", team: "Districts" },
  {
    route: "/lightbearers",
    department: "Lightbearers Community",
    team: "Districts",
  },
  {
    route: "/trailblazer",
    department: "Trailblazer Community",
    team: "Districts",
  },
  {
    route: "/praise",
    department: "Praise (Couple) Community",
    team: "Districts",
  },
  {
    route: "/gbagadaestate",
    department: "Gbagada Estate Community",
    team: "Districts",
  },
  {
    route: "/lighthouse",
    department: "Lighthouse 1&2 Community",
    team: "Districts",
  },
  {
    route: "/programsleaders",
    department: "Programs Team Leaders",
    team: "Programs",
  },
  { route: "/sapphire", department: "Sapphire ET", team: "Programs" },
  { route: "/musicians", department: "Musicians", team: "Programs" },
  { route: "/diamont", department: "Diamond ET", team: "Programs" },
  { route: "/emerald", department: "Emerald ET", team: "Programs" },
  { route: "/pearl", department: "Pearl ET", team: "Programs" },
  { route: "/probationET", department: "Probation ET", team: "Programs" },
  { route: "/greeters1", department: "Greeters 1st team", team: "Programs" },
  { route: "/greeters2", department: "Greeters 2nd team", team: "Programs" },
  { route: "/greeters3", department: "Greeters 3rd team", team: "Programs" },
  { route: "/greeters4", department: "Greeters 4th team", team: "Programs" },
  {
    route: "/hiu",
    department: "Harvesters Intelligence Unit",
    team: "Programs",
  },
  {
    route: "/mediaadmin",
    department: "Media-Administration",
    team: "Programs",
  },
  { route: "/mexperience", department: "Media-Experience", team: "Programs" },
  { route: "/mgraphics", department: "Media-Graphics", team: "Programs" },
  { route: "/mlight", department: "Media-Light", team: "Programs" },
  { route: "/mlivestream", department: "Media-Livestream", team: "Programs" },
  { route: "/mphoto", department: "Media-Photo (Capturing)", team: "Programs" },
  { route: "/mtext", department: "Media-Text & Timing", team: "Programs" },
  { route: "/mvideo", department: "Media-Video", team: "Programs" },
  { route: "/mvisuals", department: "Media-Visuals", team: "Programs" },
  { route: "/maudio", department: "Media-Audio Production", team: "Programs" },
  {
    route: "/mequipment",
    department: "Media-Equipment Management",
    team: "Programs",
  },
  { route: "/programmgt", department: "Program Management", team: "Programs" },
  { route: "/protocol", department: "Protocol", team: "Programs" },
  { route: "/sound", department: "Sound", team: "Programs" },
  { route: "/qa", department: "Quality Assurance", team: "Programs" },
  { route: "/unveildance", department: "Unveil Dance", team: "Programs" },
  { route: "/unveildrama", department: "Unveil Drama", team: "Programs" },
  { route: "/traffic", department: "Traffic", team: "Programs" },
  { route: "/usheringbimpe", department: "Ushering - Bimpe", team: "Programs" },
  { route: "/usheringqueen", department: "Ushering - Queen", team: "Programs" },
  {
    route: "/usheringiyanu",
    department: "Ushering - Iyaanu",
    team: "Programs",
  },
  { route: "/usheringtosin", department: "Ushering - Tosin", team: "Programs" },
  {
    route: "/usheringkofo",
    department: "Ushering - Kofoworola",
    team: "Programs",
  },
  { route: "/venuemgt", department: "Venue Management", team: "Programs" },
];
