export const teams = [
  {
    label: "Maturity (Prayer, Midweek)",
    value: "Maturity",
  },
  {
    label: "General Service (Finance, Facility, Etc)",
    value: "General Service",
  },
  {
    label: "Ministry (Leadership & Dev, Workforce Etc)",
    value: "Ministry",
  },
  {
    label: "Membership (Growth Track, Etc)",
    value: "Membership",
  },
  {
    label: "Programs (Choir, Ushers, Etc)",
    value: "Program",
  },
  { label: "Next Gen (Kidzone & Stir House)", value: "Next Gen" },
  {
    label: "Mission (NLP, HSAP, Evangelism, Etc)",
    value: "Mission",
  },
  { label: "District/Community", value: "District" },
  {
    label: "Interactive Groups (Singles, WOW, Etc)",
    value: "Interactive Groups",
  },
  {
    label: "Pastoral Leaders",
    value: "Pastoral Leaders",
  },
  { label: "Directional Leaders", value: "Directional Leaders" },
];

export const teamsAndDepartments = [
  {
    team: "Directional Leaders",
    department: [
      "Team Pastor",
      "Team Lead",
      "Directional Leader",
      "Admin/Subteam head",
    ],
  },
  {
    team: "Maturity",
    department: [
      "Content Development (Resources)",
      "Courses HSDC",
      "Discipleship Event",
      "Group Partnership",
      "Prayer and Bible Study",
      "Testimony Capture",
      "Admin/Subteam head",
    ],
  },
  {
    team: "General Service",
    department: [
      "Communications (DMU)",
      "Admin and Facility",
      "Finance",
      "Admin/Subteam head",
    ],
  },
  {
    team: "Ministry",
    department: [
      "Call Centre",
      "Career and Finance",
      "Discipleship, Bible Study and Prayer",
      "Elders Care",
      "House of Dorcas",
      "Kids Support",
      "Leadership Effectiveness",
      "Leadership Recruitment",
      "Leadership Training",
      "Legal Aid",
      "Medical Ministry",
      "Ministry Team Leadership",
      "Pastoral Care",
      "Prison Ministry",
      "Recruitment and Assimilation",
      "Workforce Admin",
      "Admin/Subteam head",
    ],
  },
  {
    team: "Membership",
    department: [
      "Benevolence",
      "Call Center",
      "Celebration",
      "Ceremonies",
      "Data Management",
      "Growth Track",
      "Guest Welcome",
      "Info Hub",
      "Interactors",
      "New Convert",
      "Weddings",
      "Admin/Subteam head",
    ],
  },
  {
    team: "Programs",
    department: [
      "Diamond ET",
      "Emerald ET",
      "Greeters - Team Yahweh",
      "Greeters - Team Jireh",
      "Greeters - Team Nissi",
      "Greeters - Team Rapha",
      "Harvesters Intelligence Unit",
      "Media-Administration",
      "Media-Audio Production",
      "Media-Equipment Management",
      "Media-Experience",
      "Media-Graphics",
      "Media-Light",
      "Media-Livestream",
      "Media-Photo (Capturing)",
      "Media-Text & Timing",
      "Media-Video",
      "Media-Visuals",
      "Musicians",
      "Pearl ET",
      "Program Management",
      "Programs Admin Team",
      "Protocol",
      "Quality Assurance",
      "Sapphire ET",
      "Sound",
      "Traffic",
      "Unveil",
      "Ushering - Bimpe",
      "Ushering - Iyaanu",
      "Ushering - Kofoworola",
      "Ushering - Queen",
      "Ushering - Tosin",
      "Venue Management - Boluwatife team",
      "Venue Management - Emmanuel team",
      "Venue Management - Feyisayo Phillip team",
      "Venue Management - Tosin Agbetuyi team",
      "Venue Management - Zeina team",
      "Admin/Subteam head",
    ],
  },
  {
    team: "Next Gen",
    department: [
      "Administration - Kidszone",
      "Administration - Stirhouse",
      "Learning and Development - Kidszone",
      "Learning and Development - Stirhouse",
      "Programming and Environment - Kidszone",
      "Programming and Environment - Stirhouse",
      "Reach and Partnership - Kidszone",
      "Reach and Partnership - Stirhouse",
      "Admin/Subteam head",
    ],
  },
  {
    team: "Mission",
    department: [
      "Evangelism",
      "God's Encounter",
      "HSAP",
      "Invest and Invite",
      "Publicity",
      "Sub team-Missions",
      "Target Missions",
      "Admin/Subteam head",
    ],
  },
  {
    team: "District/Community",
    department: [
      "Anagkazo Community",
      "Bethel Community",
      "Gbagada Estate Community",
      "Harmony Community",
      "Lightbearers Community",
      "Ogudu/Alapere Community",
      "Praise (Couple) Community",
      "Royal Priesthoods Community",
      "Shomolu 2 Community",
      "Sunrise Community",
      "Trailblazer Community",
    ],
  },
  {
    team: "Interactive Groups",
    department: [
      "Women of Wisdom",
      "Men of Harvest",
      "Singles",
      "Admin/Subteam head",
    ],
  },
];

export const workerRoles = [
  "Worker",
  "Cell Leader",
  "Small Group Leader",
  "Assistant HOD",
  "Zonal Leader",
  "HOD",
  "Sub Team Head",
  "Community Leader",
  "District Pastor",
  "Team Pastor/Head",
  "Directional Leader",
  "Service Pastor",
];
